name: Build and Tag Docker Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://trialyec9pb.jfrog.io
        with:
          oidc-provider-name: github-oidc-demo

      - name: Ping Artifactory
        run: jf rt ping
