name: Connect to JFrog

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://trialu0w3pd.jfrog.io
        with:
          oidc-provider-name: github-oidc-demo

      - name: Ping JFrog
        run: jf rt ping
        
